export const ADD_GALLERY = "ADD_GALLERY";
export const ADD_GALLERY_SUCCESSFUL = "ADD_GALLERY_SUCCESSFUL";
export const ADD_GALLERY_FAILED = "ADD_GALLERY_FAILED";

export const GET_GALLERY = "GET_GALLERY";
export const GET_GALLERY_SUCCESSFUL = "GET_GALLERY_SUCCESSFUL";
export const GET_GALLERY_FAILED  = "GET_GALLERY_FAILED";